### PR TITLE
Just sklearn

### PR DESCRIPTION
**Pull request by Zhuoxuan-Zhang**

### CODE REVIEW

**Comment by Zhuoxuan-Zhang** [comment]
> Why do we need this?

The script requires the Pandas library to run, but it was not listed in the requirements.txt file. Adding Pandas to the dependencies makes sure that the script has all the necessary packages to function properly when executed in different environments.

**Comment by vagos** [comment]
Nice! Can we make this run in CI?

**Comment by Zhuoxuan-Zhang** [comment]
> Ok great, please do #24 I remember there were problems running the script, are these resolved?

Yes, I think the current version is ready to be merged.

**Comment by vagos** [comment]
Looks good! Merging

**Pull request merged**
