### PR TITLE
Just media conv

### PR DESCRIPTION
**Pull request by EtomicBomb**

### CODE REVIEW

**Comment by EtomicBomb** [comment]
I am still working on this one so we shouldn't merge it until its in better shape

**Comment by vagos** [comment]
@EtomicBomb Good job! I tried running on my end in the container and it both checks fail. Does it pass on your end?

**Comment by EtomicBomb** [comment]
Yeah they both pass. That is curious

**Comment by EtomicBomb** [comment]
Can you send the md5sum of the inputs and outputs?

**Comment by EtomicBomb** [comment]
I pulled `ghcr.io/binpash/benchmarks:main` and ran `./main.sh media-conv --small`, `./main.sh media-conv`, and everything passes. Can you provide more info about the error your experiencing and about your workflow @vagos?

**Comment by vagos** [comment]
I see this one is also failing in CI

**Comment by EtomicBomb** [comment]
True. Testing locally on an ubuntu 22.04 image I get all of the mp3s failing to match.

**Comment by EtomicBomb** [comment]
I tested one of the mp3. Running md5sum on the whole file, the hashes don't match between debian and ubuntu. Hashing just the audio streams with `ffmpeg -i ./results/to_mp3.small/file_example_WAV_10MG.wav.mp3 -map 0:a -f md5 - 2>/dev/null` makes them match. The images have different versions of ffmpeg. I wonder if hashing the audio streams is robust enough.

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)

vs.

ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)

**Comment by vagos** [comment]
Great catch! Do you think you can make the CI use our container?

Hashing the audio streams is 100% okay (I think this will probably save headache in the long run).
I imagine this just requires changing the `verify.sh` script.

**Comment by vagos** [comment]
If we also want to use our container for the CI, make a separate PR :)

**Comment by EtomicBomb** [comment]
@vagos The benchmark passes CI now.

**Pull request merged**
